repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace  # удаляет пробелы в конце строк
      - id: end-of-file-fixer    # гарантирует одну пустую строку в конце файла
      - id: check-yaml           # проверяет валидность YAML
      - id: check-added-large-files  # блокирует случайные большие файлы

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black


  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]  # совместимость с Black
